### ISSUE TITLE
Upper limit to .bib size?

### ISSUE THREAD

**Issue by ghoetker** [apcshields/autocomplete-bibtex#100]
Great package. Thanks.  Tried with a very small .bib file and it worked great.  Swapped to my real .bibfile (7000+ papers, 15.5 MB) and it doesn't appear to be working.  The autocomplete just doesn't trigger.

Now, if Autocomplete just isn't up to parsing that large a file, I'd totally understand. But, I wondered if you had a sense of whether this was a file-size issue or something else. Is there any way I could check?

**Comment by mangecoeur** [comment]
I suspect that it's just too big for the autocomplete. I've only tested up
to a couple of MB. Try the search function from (bibliography search from
the command list) and see if anything appears. If not then it's definitely
a size issue. Not much to be done in that case, because the bibtex parsing
is already a bit of a mess because bibtex is itself a big mess, which makes
it very hard to optimise.

**Comment by ghoetker** [comment]
Checked and it does seem to be length.  I'm always stunned anyone can parse a single bibtex entry, much less 7000 of them.  Thank you.
