### ISSUE TITLE
How to activate?

### ISSUE THREAD

**Issue by mrmechko** [apcshields/autocomplete-bibtex#20]
It seems that `autocomplete-bibtex` only works if `autocomplete-plus` uses symbol-matching, instead of the default fuzzy-matching.  Is this the expected behavior?  If so, please add this note to the manual.

**Comment by apcshields** [comment]
Rik,



​

​This was not intended. I'll try to look into it in the next few days.




​Andrew









On Tuesday, Apr 14, 2015 at 10:13 PM, Rik <notifications@github.com>, wrote:

It seems that autocomplete-bibtex only works if autocomplete-plus uses symbol-matching, instead of the default fuzzy-matching.  Is this the expected behavior?  If so, please add this note to the manual.

**Comment by apcshields** [comment]
Rik,

I haven't been able to replicate this. Can you send me the versions of Atom, autocomplete-plus, and autocomplete-bibtex that you are using, as well as a list of any preferences that you have changed from the defaults?

Thanks,
Andrew

**Comment by mrmechko** [comment]
Hi Andrew,

Sorry for my late response.  Under stress of deadlines, I simply reset Atom and installed only the plugins that I needed (including this one). It worked fine.  I can't seem to re-engineer the problem, so I guess this issue should be closed.

Rik

**Comment by apcshields** [comment]
Rik,

I'm sorry this was part of your stress! Let me know if things start acting strangely again—changes to the underlying autocomplete library are making issues pop up and then go away again without explanation (for me, at least).

Andrew
