### ISSUE TITLE
Colon in cite key

### ISSUE THREAD

**Issue by teonbrooks** [apcshields/autocomplete-bibtex#62]
Does the autocomplete handle colons in the cite key? My default setting with bibdesk is to format the cite key with first author's last name and the year of the pub separated by a colon. It doesn't seem to fully complete the cite key when I type entries in the editor.

**Comment by apcshields** [comment]
Teon,

Punctuation in the cite keys is tricky because of the way Atom's autocomplete tokenizes text by default. I doubt colons are handled properly for your use case.

I've had very little time to spend on this project lately, but if you (or anyone else) wants to submit a pull request fixing this problem, I'll happily take a look at it.

Thanks,
Andrew
